import type { EventType, Provider, ProviderCategory, ProviderService } from "@/domain/marketplace";

export const providerCategories: ProviderCategory[] = [
  {
    id: "salones",
    name: "Locales o salones",
    image: "/images/landing/category-spaces.png",
    note: "Espacios, capacidad y equipamiento",
    active: true,
  },
  {
    id: "catering",
    name: "Catering",
    image: "/images/landing/category-catering.png",
    note: "Menús, bebidas y personal",
    active: true,
  },
  {
    id: "foto",
    name: "Fotografía y video",
    image: "/images/landing/category-photography.png",
    note: "Cobertura y entregables",
    active: true,
  },
  {
    id: "decoracion",
    name: "Decoración",
    image: "/images/landing/category-decoration.png",
    note: "Ambientación y flores",
    active: false,
  },
  {
    id: "musica",
    name: "Música, DJ y sonido",
    image: "/images/landing/category-music.png",
    note: "Música y producción sonora",
    active: false,
  },
  {
    id: "mobiliario",
    name: "Mobiliario y equipos",
    image: null,
    note: "Mesas, sillas y equipos",
    active: false,
  },
  {
    id: "entretenimiento",
    name: "Entretenimiento",
    image: null,
    note: "Experiencias para invitados",
    active: false,
  },
  {
    id: "transporte",
    name: "Transporte",
    image: null,
    note: "Traslados para tu evento",
    active: false,
  },
];

export const eventTypes: EventType[] = [
  { id: "birthday", name: "Cumpleaños" },
  { id: "wedding", name: "Matrimonio" },
  { id: "corporate", name: "Evento corporativo" },
];

export const providers: Provider[] = [
  {
    id: "jardines",
    name: "Jardines de Surco",
    location: "Santiago de Surco, Lima",
    coverage: "Lima Metropolitana",
    rating: 4.9,
    reviewCount: 86,
    image: "/images/landing/category-spaces.png",
    sponsored: true,
    description: "Un espacio flexible con jardín, salón interior y respaldo técnico.",
  },
  {
    id: "casa-barranco",
    name: "Casa Barranco",
    location: "Barranco, Lima",
    coverage: "Lima Centro",
    rating: 4.8,
    reviewCount: 64,
    image: "/images/landing/hero-event.png",
    sponsored: false,
    description: "Casona restaurada con patio central y ambientes conectados.",
  },
  {
    id: "mesa-viva",
    name: "Mesa Viva",
    location: "Miraflores, Lima",
    coverage: "Lima Metropolitana",
    rating: 4.9,
    reviewCount: 112,
    image: "/images/landing/category-catering.png",
    sponsored: false,
    description: "Cocina peruana de temporada con opciones vegetarianas y sin gluten.",
  },
  {
    id: "brasa-lima",
    name: "Brasa Lima Eventos",
    location: "San Borja, Lima",
    coverage: "Lima y Callao",
    rating: 4.7,
    reviewCount: 79,
    image: "/images/landing/category-catering.png",
    sponsored: true,
    description: "Servicio a la mesa, cocina móvil y carta adaptable al evento.",
  },
  {
    id: "luz-norte",
    name: "Luz Norte Studio",
    location: "Pueblo Libre, Lima",
    coverage: "Todo el Perú",
    rating: 4.9,
    reviewCount: 97,
    image: "/images/landing/category-photography.png",
    sponsored: false,
    description: "Documental natural con dirección discreta y entregables digitales.",
  },
  {
    id: "enfoque",
    name: "Enfoque 24",
    location: "San Isidro, Lima",
    coverage: "Lima y principales ciudades",
    rating: 4.8,
    reviewCount: 71,
    image: "/images/landing/hero-event.png",
    sponsored: true,
    description: "Retrato editorial y cobertura espontánea para eventos sociales y corporativos.",
  },
];

type ProviderServiceFixture = Omit<
  ProviderService,
  "currentUnitPrice" | "unit" | "minimumQuantity"
>;

const providerServiceFixtures: ProviderServiceFixture[] = [
  {
    id: "service-jardines",
    providerId: "jardines",
    categoryId: "salones",
    name: "Jardín y salón contemporáneo",
    startingPrice: 4800,
    priceUnit: "paquete de 8 horas",
    minimum: "Mínimo 60 invitados",
    capacity: "60–180 personas",
    packageName: "Paquete celebración",
    included: [
      "8 horas de espacio",
      "Mesas y sillas para 120",
      "Limpieza final",
      "Coordinador de sede",
    ],
    excluded: ["Catering y bar", "Decoración floral"],
    extras: ["Hora adicional S/ 380", "Pantalla y sonido S/ 650"],
    restrictions:
      "Música hasta las 2:00 a. m. El depósito de garantía de S/ 1,000 se devuelve tras la inspección.",
    supportedEventTypes: ["birthday", "wedding", "corporate"],
  },
  {
    id: "service-casa-barranco",
    providerId: "casa-barranco",
    categoryId: "salones",
    name: "Casona para celebraciones",
    startingPrice: 5250,
    priceUnit: "paquete de 7 horas",
    minimum: "Mínimo 50 invitados",
    capacity: "50–140 personas",
    packageName: "Casa completa",
    included: ["7 horas de espacio", "Mobiliario para 100", "Iluminación ambiental", "Seguridad"],
    excluded: ["Estacionamiento", "Equipos de cocina"],
    extras: ["Hora adicional S/ 420", "Montaje anticipado S/ 500"],
    restrictions:
      "No se permite pirotecnia. Proveedores externos deben acreditarse 72 horas antes.",
    supportedEventTypes: ["birthday", "wedding"],
  },
  {
    id: "service-mesa-viva",
    providerId: "mesa-viva",
    categoryId: "catering",
    name: "Buffet peruano contemporáneo",
    startingPrice: 98,
    priceUnit: "por persona",
    minimum: "Mínimo 50 personas",
    capacity: "50–350 personas",
    packageName: "Buffet celebración",
    included: [
      "Entrada, fondo y postre",
      "Menaje completo",
      "1 mozo por cada 25 personas",
      "Montaje y limpieza",
    ],
    excluded: ["Bebidas alcohólicas", "Mobiliario"],
    extras: ["Bar desde S/ 38 por persona", "Estación de café S/ 12 por persona"],
    restrictions: "Confirmación final de asistentes y dietas 7 días antes.",
    supportedEventTypes: ["birthday", "wedding", "corporate"],
  },
  {
    id: "service-mesa-viva-bar",
    providerId: "mesa-viva",
    categoryId: "catering",
    name: "Bar de cócteles",
    startingPrice: 38,
    priceUnit: "por persona",
    minimum: "Mínimo 30 personas",
    capacity: "30–250 personas",
    packageName: "Bar celebración",
    included: ["Bartender", "Insumos", "Cristalería"],
    excluded: ["Mobiliario"],
    extras: ["Hora adicional S/ 250"],
    restrictions: "La selección final se confirma en la cotización.",
    supportedEventTypes: ["birthday", "wedding", "corporate"],
  },
  {
    id: "service-brasa-lima",
    providerId: "brasa-lima",
    categoryId: "catering",
    name: "Cena servida de tres tiempos",
    startingPrice: 115,
    priceUnit: "por persona",
    minimum: "Mínimo 40 personas",
    capacity: "40–250 personas",
    packageName: "Cena servida",
    included: [
      "Tres tiempos",
      "Personal de cocina y salón",
      "Vajilla y cristalería",
      "Transporte en Lima",
    ],
    excluded: ["Bar", "Torta"],
    extras: ["Cóctel de bienvenida S/ 18 por persona", "Menú infantil S/ 58"],
    restrictions: "Requiere acceso a agua y energía. Cocina móvil sujeta a visita técnica.",
    supportedEventTypes: ["birthday", "corporate"],
  },
  {
    id: "service-luz-norte",
    providerId: "luz-norte",
    categoryId: "foto",
    name: "Fotografía y película de evento",
    startingPrice: 3200,
    priceUnit: "paquete de 8 horas",
    minimum: "Cobertura mínima 6 horas",
    capacity: "1–3 profesionales",
    packageName: "Historia completa",
    included: [
      "Fotógrafo y videógrafo",
      "8 horas de cobertura",
      "Galería de 500 fotos",
      "Película de 6–8 minutos",
    ],
    excluded: ["Álbum impreso", "Viajes fuera de Lima"],
    extras: ["Dron S/ 450", "Hora extra S/ 320", "Álbum S/ 680"],
    restrictions: "Entrega en 30 días. Dos rondas de edición de video. Uso personal incluido.",
    supportedEventTypes: ["birthday", "wedding", "corporate"],
  },
  {
    id: "service-enfoque",
    providerId: "enfoque",
    categoryId: "foto",
    name: "Cobertura fotográfica editorial",
    startingPrice: 2400,
    priceUnit: "paquete de 6 horas",
    minimum: "Cobertura mínima 4 horas",
    capacity: "1–2 profesionales",
    packageName: "Editorial 6",
    included: [
      "2 fotógrafos",
      "6 horas",
      "Galería de 350 fotos",
      "Entrega prioritaria de 20 fotos",
    ],
    excluded: ["Video", "Dron"],
    extras: ["Hora extra S/ 280", "Segundo local S/ 250"],
    restrictions: "Entrega completa en 21 días. Una ronda de ajustes de color.",
    supportedEventTypes: ["birthday", "wedding", "corporate"],
  },
];

const servicePricing: Record<string, Pick<ProviderService, "unit" | "minimumQuantity">> = {
  "service-jardines": { unit: "fixed", minimumQuantity: 1 },
  "service-casa-barranco": { unit: "fixed", minimumQuantity: 1 },
  "service-mesa-viva": { unit: "person", minimumQuantity: 50 },
  "service-mesa-viva-bar": { unit: "person", minimumQuantity: 30 },
  "service-brasa-lima": { unit: "person", minimumQuantity: 40 },
  "service-luz-norte": { unit: "fixed", minimumQuantity: 1 },
  "service-enfoque": { unit: "fixed", minimumQuantity: 1 },
};

export const providerServices: ProviderService[] = providerServiceFixtures.map((service) => ({
  ...service,
  currentUnitPrice: service.startingPrice,
  ...servicePricing[service.id],
}));
